apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-inventory-api
  labels:
    app: ecommerce-inventory   # 🔥 agrupa toda la app
    service: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-inventory
  template:
    metadata:
      labels:
        app: ecommerce-inventory
    spec:
      containers:
        - name: ecommerce-inventory
          image: host.docker.internal:5000/ecommerce-order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: USERS_SERVICE_URL
              value: http://ecommerce-inventory:8080   # 🔥 AÑADIDO
            - name: DB_URL
              value: jdbc:postgresql://postgres:5432/amazon_ecommerce_inventory
            - name: DB_USER
              value: postgres
            - name: DB_PASS
              value: postgres
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SCHEMA_REGISTRY
              value: http://schema-registry:8081